# Generated by Django 4.1 on 2022-09-02 20:04

import datetime
from django.db import migrations, models
import timedelta.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MinMaxTestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min",
                    timedelta.fields.TimedeltaField(
                        min_value=datetime.timedelta(days=1)
                    ),
                ),
                (
                    "max",
                    timedelta.fields.TimedeltaField(
                        max_value=datetime.timedelta(days=1)
                    ),
                ),
                (
                    "minmax",
                    timedelta.fields.TimedeltaField(
                        max_value=datetime.timedelta(days=7),
                        min_value=datetime.timedelta(days=1),
                    ),
                ),
            ],
        ),
    ]
